// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luerxoaemweiqzafkpuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZXJ4b2FlbXdlaXF6YWZrcHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDgwMTYsImV4cCI6MjA2MTA4NDAxNn0.7Sv0GFTD44SVCQKNwWqVjoYbfAkXBbH_Fh0T0DuPolY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);